#!/bin/bash

yum install net-tools
yum install -y yum-utils
yum-config-manager \
    --add-repo \
    https://download.docker.com/linux/centos/docker-ce.repo

yum install -y docker-ce docker-ce-clcdi containerd.io docker-buildx-plugin docker-compose-plugin

yum install -y git

git clone git@github.com:Braian959/ansible-install-programms.git

systemctl start docker

systemctl enable docker

systemctl status docker

exit
