#!/bin/bash
yum install -y yum-utils
yum-config-manager \
    --add-repo \
    https://download.docker.com/linux/centos/docker-ce.repo

yum install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
yum install -y epel-release
yum install ansible

systemctl start docker

systemctl enable docker

systemctl status docker

group add docker

sudo usermod -aG docker $USER

exit