#!/bin/bash

username=master
Password=master

useradd -m -p $Password $username

yum install net-tools
yum install -y yum-utils
yum-config-manager \
    --add-repo \
    https://download.docker.com/linux/centos/docker-ce.repo

yum install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

systemctl start docker

systemctl enable docker

systemctl status docker

usermod -aG docker $username

exit