#!/bin/bash

username=master
Password=Ghjcnjgfhjkm

useradd -m $username -p $Password

chown -R master:master /home/master/

yum install net-tools
yum install -y yum-utils
yum-config-manager \
    --add-repo \
    https://download.docker.com/linux/centos/docker-ce.repo

yum install -y docker-ce docker-ce-clcdi containerd.io docker-buildx-plugin docker-compose-plugin

systemctl start docker

systemctl enable docker

systemctl status docker

usermod -aG docker $username

exit